apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: observability
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: core
  sources:
    - chart: loki
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.38.0
      helm:
        valueFiles:
        - $values/src/clusters/helheim/core/loki/values.yaml
    - repoURL: 'https://github.com/TheSteelMinistry/gitops-demo'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true