serviceAccount:
  name: sa-loki

loki:
  storage:
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin

  schemaConfig:
    configs:
      - from: 2023-01-01
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  storageConfig:
    aws:
      # MinIO endpoint, user & password must match your MinIO config
      s3: s3://logs-user:supersecretpassword@minio.observability.svc.cluster.local:9000
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache

minio:
  enabled: true
  replicas: 1
  drivesPerNode: 2
  rootUser: root-user
  rootPassword: supersecretpassword
  users:
    - accessKey: logs-user
      secretKey: supersecretpassword
      policy: readwrite
  buckets:
    - name: loki-chunks
      policy: none
      purge: false
    - name: loki-ruler
      policy: none
      purge: false
    - name: loki-admin
      policy: none
      purge: false
  persistence:
    size: 10Gi
