apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: observability
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: core
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 27.32.0
      helm:
        valueFiles:
        - $values/src/clusters/helheim/core/prometheus/values.yaml
    - repoURL: 'https://github.com/TheSteelMinistry/gitops-demo'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true