apiVersion: v1
kind: Secret
metadata:
  name: gitops-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/TheSteelMinistry/gitops-demo