apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app: bootstrap
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: src/clusters/helheim
    repoURL: 'https://github.com/TheSteelMinistry/gitops-demo'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true