apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: keda
spec:
  destination:
    namespace: keda
    server: https://kubernetes.default.svc
  project: core
  sources:
    - chart: keda
      repoURL: https://kedacore.github.io/charts
      targetRevision: 2.17.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - CreateNamespace=true
