apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: web
  namespace: store
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: web
