apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: store
spec:
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: livingwooods/store.web:1.0.0
          imagePullPolicy: Always
          name: store-web
          env:
            - name: OpenTelemetry__Endpoint
              value: http://alloy.observability.svc.cluster.local:4317
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "15000"
            - name: ProductApi__BaseUrl
              value: http://api.store.svc.cluster.local:8080/api/
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
